default_install_hook_types:
  - commit-msg
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      # Windows compatibility
      - id: check-case-conflict
      - id: check-illegal-windows-names
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.35
    hooks:
      - id: pymarkdown
        args:
          - -d
          - no-multiple-blanks,line-length
          - scan
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: fmt
        name: cargo-fmt
      - id: clippy
        name: cargo-clippy
      - id: clippy
        name: cargo-clippy-tests
        args: ["--tests", "--", "-D", "warnings"]
  - repo: https://github.com/jadinm/rust-pre-commit-hooks
    rev: 1.2.1
    hooks:
      - id: cargo-audit
      - id: cargo-deny
