name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install cargo binaries (uses cargo binstall to go faster)
      - uses: taiki-e/install-action@cargo-audit
      - uses: taiki-e/install-action@cargo-deny
      - uses: taiki-e/install-action@cargo-binstall

      # pre-commit run
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.1

      # Rust tests
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

      # Run program on self
      - name: Test offline-package on self
        run: cargo run --bin cargo-offline-package offline-package example_settings
      - name: Test offline-install on self (skipping custom & git steps)
        run: |
          mkdir tmp
          cd tmp
          cargo run --manifest-path ../Cargo.toml --bin cargo-offline-install -- offline-install --skip git-push --skip custom ../offline-vendoring.tar.gz
